apiVersion: apps/v1
kind: Deployment
metadata:
  name: API_TESTER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: API_TESTER
  template:
    metadata:
      labels:
        app: API_TESTER
    spec:
      containers:
      - name: API_TESTER
        image: API_TESTER:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: API_TESTER
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: API_TESTER