apiVersion: apps/v1
kind: Deployment
metadata:
  name: API_TESTER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: API_TESTER
  template:
    metadata:
      labels:
        app: API_TESTER
    spec:
      containers:
      - name: numbers-api
        image: API_TESTER:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /average
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /average
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5